In [1]:
import pandas as pd 
import numpy as np

df = pd.read_csv("healthcare_dataset.csv")

pd.set_option('display.max_columns', None)

df.head(10)

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal
5,EMILY JOHNSOn,36,Male,A+,Asthma,2023-12-20,Taylor Newton,Nunez-Humphrey,UnitedHealthcare,48145.110951,389,Urgent,2023-12-24,Ibuprofen,Normal
6,edwArD EDWaRDs,21,Female,AB-,Diabetes,2020-11-03,Kelly Olson,Group Middleton,Medicare,19580.872345,389,Emergency,2020-11-15,Paracetamol,Inconclusive
7,CHrisTInA MARtinez,20,Female,A+,Cancer,2021-12-28,Suzanne Thomas,"Powell Robinson and Valdez,",Cigna,45820.462722,277,Emergency,2022-01-07,Paracetamol,Inconclusive
8,JASmINe aGuIlaR,82,Male,AB+,Asthma,2020-07-01,Daniel Ferguson,Sons Rich and,Cigna,50119.222792,316,Elective,2020-07-14,Aspirin,Abnormal
9,ChRISTopher BerG,58,Female,AB-,Cancer,2021-05-23,Heather Day,Padilla-Walker,UnitedHealthcare,19784.631062,249,Elective,2021-06-22,Paracetamol,Inconclusive

### Exploratory Data Analysis

In [2]:
df.isnull().sum()

Name                  0
Age                   0
Gender                0
Blood Type            0
Medical Condition     0
Date of Admission     0
Doctor                0
Hospital              0
Insurance Provider    0
Billing Amount        0
Room Number           0
Admission Type        0
Discharge Date        0
Medication            0
Test Results          0
dtype: int64

In [3]:
df.duplicated().sum()

np.int64(534)

In [4]:
df.drop_duplicates(inplace=True)

In [5]:
df.duplicated().sum()

np.int64(0)

In [6]:
df.info()

<class 'pandas.DataFrame'>
Index: 54966 entries, 0 to 55499
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Name                54966 non-null  str
 1   Age                 54966 non-null  int64
 2   Gender              54966 non-null  str
 3   Blood Type          54966 non-null  str
 4   Medical Condition   54966 non-null  str
 5   Date of Admission   54966 non-null  str
 6   Doctor              54966 non-null  str
 7   Hospital            54966 non-null  str
 8   Insurance Provider  54966 non-null  str
 9   Billing Amount      54966 non-null  float64
 10  Room Number         54966 non-null  int64
 11  Admission Type      54966 non-null  str
 12  Discharge Date      54966 non-null  str
 13  Medication          54966 non-null  str
 14  Test Results        54966 non-null  str
dtypes: float64(1), int64(2), str(12)
memory usage: 6.7 MB

In [12]:
df.describe(include=[int , float])

                Age  Billing Amount   Room Number
count  54966.000000    54966.000000  54966.000000
mean      51.535185    25544.306284    301.124404
std       19.605661    14208.409711    115.223143
min       13.000000    -2008.492140    101.000000
25%       35.000000    13243.718641    202.000000
50%       52.000000    25542.749145    302.000000
75%       68.000000    37819.858159    401.000000
max       89.000000    52764.276736    500.000000

In [61]:
df['Name'] = df['Name'].str.title()

In [22]:
#Age distribution
df['Age'].describe()

count    54966.000000
mean        51.535185
std         19.605661
min         13.000000
25%         35.000000
50%         52.000000
75%         68.000000
max         89.000000
Name: Age, dtype: float64

In [23]:
#Gender Analysis
df['Gender'].value_counts()

Gender
Male      27496
Female    27470
Name: count, dtype: int64

In [24]:
#commmon medical condition
df['Medical Condition'].value_counts().head(10)

Medical Condition
Arthritis       9218
Diabetes        9216
Hypertension    9151
Obesity         9146
Cancer          9140
Asthma          9095
Name: count, dtype: int64

### Billing Distribution

In [48]:
print(np.percentile(billing,25))
print(np.percentile(billing,50))
print(np.percentile(billing,75))
print(np.percentile(billing,95))

13243.71864076912
25542.749144555833
37819.85815919015
47638.266646337855

In [29]:
df.groupby('Medical Condition')['Billing Amount'].mean().sort_values(ascending=True)

Medical Condition
Cancer          25152.322947
Hypertension    25503.058720
Arthritis       25511.783246
Asthma          25633.461696
Diabetes        25660.478635
Obesity         25804.361902
Name: Billing Amount, dtype: float64

### Insurance Provider Analysis

In [31]:
df.groupby('Insurance Provider')['Billing Amount'].mean()

Insurance Provider
Aetna               25549.689648
Blue Cross          25603.460603
Cigna               25525.998670
Medicare            25628.320208
UnitedHealthcare    25414.506208
Name: Billing Amount, dtype: float64

### Gender Analysis

In [32]:
df.groupby('Gender')['Billing Amount'].mean()

Gender
Female    25474.098266
Male      25614.447915
Name: Billing Amount, dtype: float64

### Test Result Analysis

### Top 10 highest cost patients

In [77]:
billing = df['Billing Amount'].values
top_10 = np.percentile(billing , 90)
top_pateints = df[
    df['Billing Amount'] >= top_10 ]
top_pateints.shape

(5497, 17)

In [34]:
df.groupby('Test Results')['Billing Amount'].mean()

Test Results
Abnormal        25544.035142
Inconclusive    25637.338530
Normal          25452.221742
Name: Billing Amount, dtype: float64

### Age Analysis

In [35]:
bins = [0,18,35,50,65,100]

labels = ['0-18','19-35','36-50','51-65','65+']

df['Age_Group'] = pd.cut(
    df['Age'],
    bins=bins,
    labels=labels
)

df.groupby('Age_Group')['Billing Amount'].mean()

Age_Group
0-18     26746.284926
19-35    25519.828004
36-50    25513.013947
51-65    25663.869336
65+      25431.005853
Name: Billing Amount, dtype: float64

### Patients above average cost

In [81]:
average_cost = np.mean(billing)
avg_cost_patients = df[
    df['Billing Amount'] > average_cost]
avg_cost_patients.shape[0]

27479